apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-list-cm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  customers: |
    Liam
    Olivia
    Noah
    Emma
    Oliver
    Ava
    Elijah
    Charlotte
    William
    Sophia
    James
    Amelia
    Benjamin
    Harper
    Lucas
    Evelyn
    Henry
    Abigail
    Alexander
    Emily
    Samuel
    Elizabeth
    Michael
    Sofia
    Daniel
    Avery
    Matthew
    Ella
    Joseph
    Scarlett
    David
    Grace
    Jackson
    Lily
    Theodore
    Chloe
    Owen
    Mia
    Jack
    Harper
